name: Pytest - CI for Docker

on:
  pull_request:    
    branches:
    - develop  
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build -t paramak_tfcoil_rectroundcorner .
        docker run --rm paramak_tfcoil_rectroundcorner /bin/bash -c "bash run_tests.sh && curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${8cd3ec3f-7b8a-440b-bfec-7e61478c41e8}"