name: Pytest - CI for Docker

on:
  pull_request:    
    branches:
    - develop  
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        ci_env=`bash <(curl -s https://codecov.io/env)`
        docker run $ci_env -e CI=true ...
        docker build -t paramak_tfcoil_rectroundcorner .
        docker run --rm paramak_tfcoil_rectroundcorner /bin/bash -c "bash run_tests.sh" 
        ./codecov -t ${{ secrets.CODECOV_TOKEN }}